On 116 new remove buttons
SWEseniordesign/senior-design pull request #31
Opened 2023-02-14 01:33 UTC by gracekiely

2023-02-15 15:57 UTC, dunc415 commented
Fix conflicts plz

2023-02-16 15:27 UTC, dunc415 requested changes

2023-02-16 15:27 UTC, dunc415 commented on src/pages/Home/Home.js
> +                        { <Button variant="contained" onClick={handleCreateData} sx={{background: COLOR_PALETTE.NAVY_BLUE, width: '136px', height: '48px', fontSize: '16px'}}>CREATE DATA</Button> }
This is still in the screen.

2023-03-02 17:37 UTC, gracekiely commented on src/pages/Home/Home.js
> +                        { <Button variant="contained" onClick={handleCreateData} sx={{background: COLOR_PALETTE.NAVY_BLUE, width: '136px', height: '48px', fontSize: '16px'}}>CREATE DATA</Button> }
removed now

2023-03-07 01:39 UTC, dunc415 approved these changes

2023-03-08 18:02 UTC, dunc415 approved these changes

2023-03-08 18:02 UTC, merged